export let item = [
  {
    id: 1,
    display: true,
    name: "Bigger Satisfaction",
    price: 9.99,
    description: "Bigger Satisfaction",
    url: "https://iili.io/H1ayYla.png",
  },
  {
    id: 2,
    display: true,
    name: "Breakfast Promo",
    price: 8.99,
    description: "Breakfast Promo",
    url: "https://iili.io/H1ay7Kg.png",
  },
  {
    id: 3,
    display: true,
    name: "Brekkie Special",
    price: 6.99,
    description: "Brekkie Special",
    url: "https://iili.io/H1ayaUJ.png",
  },
  {
    id: 4,
    display: true,
    name: "Chill Together",
    price: 9.99,
    description: "Chill Together",
    url: "https://iili.io/H1cFcBV.png",
  },
  {
    id: 5,
    display: true,
    name: "Classic Favourites",
    price: 12.99,
    description: "Classic Favourites",
    url: "https://iili.io/H1ayuoP.png",
  },
  {
    id: 6,
    display: true,
    name: "Crunchy Bites",
    price: 16.99,
    description: "Crunchy Bites",
    url: "https://iili.io/H1cF0rP.png",
  },
  {
    id: 7,
    display: true,
    name: "Double Goodness",
    price: 9.99,
    description: "Double Goodness",
    url: "https://iili.io/H1ay0RR.png",
  },
  {
    id: 8,
    display: true,
    name: "Monday Breakfast Special 1",
    price: 5.5,
    description: "Monday Breakfast Special 1",
    url: "https://iili.io/H1cFI29.png",
  },
  {
    id: 9,
    display: true,
    name: "Monday Breakfast Special 2",
    price: 5.5,
    description: "Monday Breakfast Special 2",
    url: "https://iili.io/H1cFAmb.png",
  },
  {
    id: 10,
    display: true,
    name: "Monday Breakfast Special 3",
    price: 7.5,
    description: "Monday Breakfast Special 3",
    url: "https://iili.io/H1cF7hx.png",
  },
  {
    id: 11,
    display: true,
    name: "Monday Breakfast Special 4",
    price: 7.5,
    description: "Monday Breakfast Special 4",
    url: "https://iili.io/H1cFGYF.png",
  },
  {
    id: 12,
    display: true,
    name: "Monday Breakfast Special 5",
    price: 6.5,
    description: "Monday Breakfast Special 5",
    url: "https://iili.io/H1cFE21.png",
  },
  {
    id: 13,
    display: true,
    name: "Morning Surprise",
    price: 8.99,
    description: "Morning Surprise",
    url: "https://iili.io/H1ay1Np.png",
  },
  {
    id: 14,
    display: true,
    name: "Perfect Pair",
    price: 9.99,
    description: "Perfect Pair",
    url: "https://iili.io/H1ayMxI.png",
  },
  {
    id: 15,
    display: true,
    name: "Spicy Surprise",
    price: 9.99,
    description: "Spicy Surprise",
    url: "https://iili.io/H1cFe4I.png",
  },
  {
    id: 16,
    display: true,
    name: "Unbeatable Duo",
    price: 10.5,
    description: "Unbeatable Duo",
    url: "https://iili.io/H1ayVVt.png",
  },
  {
    id: 17,
    display: true,
    name: "Weekend Breakfast Special 1",
    price: 21,
    description: "Weekend Breakfast Special 1",
    url: "https://iili.io/H1cFXTJ.png",
  },
  {
    id: 18,
    display: true,
    name: "Weekend Breakfast Special 2",
    price: 23,
    description: "Weekend Breakfast Special 2",
    url: "https://iili.io/H1cFjQR.png",
  },
];
